xcodeproj 'HotOrNot/HotOrNot.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'HotOrNot' do
pod 'LayerKit'
end

target 'seflieclub-tests' do
pod 'LayerKit'
end

