#!/bin/bash

#- info.plist path
plist=${PROJECT_DIR}/${INFOPLIST_FILE}

#- get build version & increment
buildVersion=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" $plist)
buildVersion=$(($buildVersion + 1))

#-// for hex increment //-#
#-- buildVersion=$((0x$buildVersion))
#-- buildVersion=$(printf "%X" $buildVersion)

#- update plist
/usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildVersion" $plist


#- terminate w/o error
exit 0;

##]=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=[#]=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=[##

#!/bin/bash
#- plist=${PROJECT_DIR}/${INFOPLIST_FILE}
#- buildVersion=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" $plist)
#- buildVersion=$(($buildVersion + 1))
#-- buildVersion=$((0x$buildVersion)) --HEX--
#-- buildVersion=$(printf "%X" $buildVersion) --HEX--
#- /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $buildVersion" $plist
#- exit 0