#!/bin/bash


#-- check for username param
if [ ! $1 ]; then 
	exit 1;
else username="$1"; fi

#-- set tier to live
subdomain_api="admin"

 #-- api attribs
block_url="http://${subdomain_api}.letsvolley.com/admin/block_user.php"
wipe_url="http://${subdomain_api}.letsvolley.com/admin/wipe_user.php"
login_api="volley:\$uper\$mack"


# call block user
printf "Finding user '%s' from (%s.letsvolley.com)... " "${username}" "${subdomain_api}"
result=$(curl --request POST --location "${block_url}" --user "${login_api}" --data-urlencode "username=${username}" --silent | sed -E 's/\<(\/)?pre\>//g' | grep --max-count 1 --only-matching "${username}")

#-- check for user json
if [ -n "$result" ]; then echo "Completed!"
	
else echo "Not found!"; fi


#-- exit w/o error
exit 0;




#// dev
#-- http://api-stage.letsvolley.com/admin/wipe_user.php

#// live
#-- http://admin.letsvolley.com/admin/wipe_user.php


#// not found result
#-- result="Array ( [0] => blocking: [1] => BIM_Model_User Object ( ) )"
