#!/bin/bash

#-- change dir to script's, up one
if [ $(pwd) != `dirname $0` ]; then cd `dirname $0`; fi
cd ../

#-- check for zerver & node processes running... the force kill
if [ `ps -cj | grep zerver | awk '{print $2}'` ]; then kill -9 $(ps -cj | grep zerver | awk '{print $2}'); fi
if [ `ps -cj | grep node | awk '{print $2}'` ]; then kill -9 $(ps -cj | grep node | awk '{print $2}'); fi

#-- deploy dir already exists, remove it!
if [ -d ../03_DEPLOY/starter-kit ]; then rm -Rf ../03_DEPLOY/starter-kit; fi


#-- copy /web dir over to deploy/
cp -R starter-kit/web/ ../03_DEPLOY/starter-kit


#-- (re)start up zerver
cd ../03_DEPLOY/starter-kit && zerver ./


#-- return to proj root
cd ../../


#-- teminate w/o error
exit 0;