#!/bin/bash

app_name="Selfieclub"
prov_name="${app_name} Ad Hoc"

if [[ `pwd` != `dirname $0` ]]; then 
	cd `dirname $0`; fi

cd ../

build_ts=$(date +%Y%m%d_%H%M%S)
printf "BUILD STARTS @ [%s]\n" "${build_ts}"

src_dir="$(pwd)/ios/HotOrNot"
info_plist="${src_dir}/HotOrNot/HotOrNot-Info.plist"
deploy_dir="${src_dir}/../_deploy/${build_ts}"

name_arc="${app_name}-${build_ver}.xcarchive"
name_ipa="${app_name}.ipa"


if [ ! -d "$deploy_dir" ]; then
	mkdir -p "${deploy_dir}"; fi

find "${deploy_dir}" -type f -name "*.ipa" -exec rm {} \;

#--

cd "${src_dir}"
xcodebuild -scheme HotOrNot archive -archivePath "${deploy_dir}/${app_name}.xcarchive"

build_ver=$(/usr/libexec/PlistBuddy -c "Print CFBundleVersion" "${info_plist}")
name_arc="${app_name}-${build_ver}.xcarchive"
mv "${deploy_dir}/${app_name}.xcarchive" "${deploy_dir}/${name_arc}"

xcodebuild -exportArchive -exportFormat ipa -archivePath "${deploy_dir}/${name_arc}" -exportPath "${deploy_dir}/${name_ipa}" -exportProvisioningProfile "${prov_name}"

printf "BUILD COMPLETES @ [%s]\n" `date +%Y%m%d_%H%M%S`

#--echo "$(date +%Y%m%d_%H%M%S)"
open -a HockeyApp "${deploy_dir}/${name_arc}"


exit 0;
