#!/bin/bash

asset_grp=$1
assets_dir=/Volumes/Skuld/labor/clients/built_in_menlo/projects/hotornot/media/skinning/06052013-tmp/PARTS
resources_dir=/Volumes/Skuld/labor/clients/built_in_menlo/projects/hotornot/ios/HotOrNot/HotOrNot/Resources_test


for lproj in `find $resources_dir -type d -name '*.lproj'`; do 
	locale_id=`basename "${lproj}"`
	
	find ${assets_dir} -type f -name "${asset_grp}" -exec cp {} "${lproj}" \;
	printf "Copying %s to %s...\n\n" "${asset_grp}" `basename "${lproj}"`
done


exit 0;