#!/bin/bash


if [ ! ${!#} ]; then
	exit 0;
else
	username="${!#}"; fi


isStage_flg=false
while getopts "s" optname # --//> there's a '-s'
	do # --/ loop thru the params
		case "$optname" in #  -/> set flag based on char

		"s") # )-/> passed in '-s'
			isStage_flg=true
			;;

		"?") # )-/> anything else
			echo "Unknown option $OPTARG"
			exit 1;
			;;

		":") # )-/> no arg
			echo "No argument value for option $OPTARG"
			exit 1;
			;;

		*) # )-/> shouldn't occur
			echo "Unknown error"
			exit 1;
			;;
	esac
done






 # --/> use stage 
if $isStage_flg; then api_subdomain="admin-stage"
else api_subdomain="admin"; fi

block_url="http://${api_subdomain}.letsvolley.com/admin/block_user.php"
wipe_url="http://${api_subdomain}.letsvolley.com/admin/wipe_user.php"


# call block user
printf "Blocking user '%s' from (%s.letsvolley.com)... " "${username}" "${api_subdomain}"
result=$(curl --request POST --location "${block_url}" --user "volley:\$uper\$mack" --data-urlencode "username=${username}" --silent)
isUser=$(echo "${result}" | sed 's/\[//g; s/\]//g' | grep --max-count 1 --only-matching "${username}")

#-- check for user json
if [ "$isUser" ]; then printf "Completed!\n"
else printf "Not found!\n"; fi

# call wipe user
printf "Wiping user '%s' from (%s.letsvolley.com)... " "${username}" "${api_subdomain}"
result=$(curl --request POST --location "${wipe_url}" --user "volley:\$uper\$mack" --data-urlencode "username=${username}" --silent)
isUser=$(echo "${result}" | sed 's/\[//g; s/\]//g' | grep --max-count 1 --only-matching "${username}")

#-- check for user json
if [ "$isUser" ]; then printf "Completed!\n"
else printf "Not found!\n"; fi


#-- exit w/o error
exit 0;




#// dev
#-- http://api-stage.letsvolley.com/admin/wipe_user.php

#// staging / avicii
#-- http://api-dev.letsvolley.com/admin/wipe_user.php

#// live
#-- http://130.letsvolley.com/admin/wipe_user.php
#-- http://admin.letsvolley.com/admin/wipe_user.php

